#!/usr/bin/env python3
# ==============================================================================
# LUMINA EDGE :: System Optimizer (Cross-Platform)
# Objective: Free system memory before LLM inference
# Supports: Linux (systemd), Windows, macOS
# ==============================================================================

import sys
import os
import platform
import subprocess
import json
from pathlib import Path

class Colors:
    """ANSI color codes"""
    CYAN = '\033[0;36m'
    GREEN = '\033[0;32m'
    YELLOW = '\033[1;33m'
    RED = '\033[0;31m'
    GRAY = '\033[0;90m'
    NC = '\033[0m'

def log_info(msg: str):
    """Info message"""
    print(f"{Colors.CYAN}[INFO]{Colors.NC} {msg}")

def log_success(msg: str):
    """Success message"""
    print(f"{Colors.GREEN}[+]{Colors.NC} {msg}")

def log_warn(msg: str):
    """Warning message"""
    print(f"{Colors.YELLOW}[WARN]{Colors.NC} {msg}")

def log_error(msg: str):
    """Error message"""
    print(f"{Colors.RED}[ERROR]{Colors.NC} {msg}")

def get_platform() -> str:
    """Get OS name"""
    return platform.system().lower()

def get_memory_stats() -> int:
    """Get available memory in MB"""
    system = get_platform()
    
    try:
        if system == 'linux':
            with open('/proc/meminfo', 'r') as f:
                for line in f:
                    if line.startswith('MemAvailable'):
                        return int(line.split()[1]) // 1024
        elif system == 'windows':
            import ctypes
            kernel32 = ctypes.windll.kernel32
            c_ulong = ctypes.c_ulong
            class MemoryStatus(ctypes.Structure):
                _fields_ = [
                    ("dwLength", c_ulong),
                    ("dwMemoryLoad", c_ulong),
                    ("ullTotalPhys", ctypes.c_ulonglong),
                    ("ullAvailPhys", ctypes.c_ulonglong),
                    ("ullTotalPageFile", ctypes.c_ulonglong),
                    ("ullAvailPageFile", ctypes.c_ulonglong),
                    ("ullTotalVirtual", ctypes.c_ulonglong),
                    ("ullAvailVirtual", ctypes.c_ulonglong),
                    ("ullExtendedVirtual", ctypes.c_ulonglong),
                ]
            stat = MemoryStatus()
            stat.dwLength = ctypes.sizeof(MemoryStatus)
            if kernel32.GlobalMemoryStatusEx(ctypes.byref(stat)):
                return stat.ullAvailPhys // (1024 * 1024)
        elif system == 'darwin':
            result = subprocess.run(['vm_stat'], capture_output=True, text=True)
            # Parse darwin memory (simplified)
            for line in result.stdout.split('\n'):
                if 'Pages free' in line:
                    pages_free = int(line.split(': ')[1].split('.')[0])
                    return (pages_free * 4) // 1024  # 4KB pages
    except Exception as e:
        log_warn(f"Could not read memory: {e}")
    
    return 0

def optimize_linux() -> int:
    """Optimize Linux system"""
    log_info("Optimizing Linux system...")
    
    mem_before = get_memory_stats()
    stopped_count = 0
    
    # Check for root
    have_root = os.geteuid() == 0 if hasattr(os, 'geteuid') else True
    
    if not have_root:
        log_warn("Not running as root. Some optimizations will be skipped.")
        log_warn("Re-run with sudo for full memory reclamation.")
    
    # 1. Drop caches
    if have_root:
        try:
            log_success("Syncing filesystem and dropping caches...")
            subprocess.run(['sync'], check=False)
            with open('/proc/sys/vm/drop_caches', 'w') as f:
                f.write('3')
            log_info("Page cache, dentries, and inodes freed.")
        except Exception as e:
            log_warn(f"Cache drop failed: {e}")
    
    # 2. Compact memory
    if have_root and Path('/proc/sys/vm/compact_memory').exists():
        try:
            log_success("Compacting memory...")
            with open('/proc/sys/vm/compact_memory', 'w') as f:
                f.write('1')
        except Exception as e:
            log_warn(f"Memory compaction failed: {e}")
    
    # 3. Stop services
    services_to_stop = [
        'tracker-miner-fs-3.service',
        'tracker-miner-fs.service',
        'packagekit.service',
        'fwupd.service',
        'snapd.service',
        'unattended-upgrades.service',
    ]
    
    restore_script_path = Path('/tmp/lumina_restore_services.sh')
    with open(restore_script_path, 'w') as f:
        f.write('#!/usr/bin/env bash\n')
        f.write('# Auto-generated by optimize_system.py — safe to delete\n')
        f.write('# Run with sudo to restore services\n')
    
    if have_root:
        for svc in services_to_stop:
            try:
                result = subprocess.run(['systemctl', 'is-active', '--quiet', svc], 
                                      capture_output=True)
                if result.returncode == 0:
                    log_warn(f"Suspending {svc}...")
                    subprocess.run(['systemctl', 'stop', svc], capture_output=True)
                    with open(restore_script_path, 'a') as f:
                        f.write(f"systemctl start {svc} 2>/dev/null || true\n")
                    stopped_count += 1
            except Exception as e:
                log_warn(f"Could not stop {svc}: {e}")
    
    # 4. Pause tracker (GNOME)
    try:
        tracker_cmd = None
        if subprocess.run(['which', 'tracker3'], capture_output=True).returncode == 0:
            tracker_cmd = ['tracker3', 'pause', '-s', 'Lumina Edge optimization']
        elif subprocess.run(['which', 'tracker'], capture_output=True).returncode == 0:
            tracker_cmd = ['tracker', 'daemon', '--pause=Lumina Edge optimization']
        
        if tracker_cmd:
            log_warn("Pausing GNOME Tracker indexer...")
            subprocess.run(tracker_cmd, capture_output=True)
    except Exception as e:
        log_warn(f"Tracker pause failed: {e}")
    
    # 5. Transparent huge pages
    thp_path = Path('/sys/kernel/mm/transparent_hugepage/enabled')
    if have_root and thp_path.exists():
        try:
            log_success("Setting Transparent Huge Pages to madvise...")
            with open(thp_path, 'w') as f:
                f.write('madvise')
        except Exception as e:
            log_warn(f"THP setting failed: {e}")
    
    # 6. CPU frequency governor
    try:
        result = subprocess.run(['sudo', 'cpupower', 'frequency-set', '-g', 'performance'], capture_output=True)
        if result.returncode == 0:
            log_success("CPU frequency governor set to performance")
        else:
            log_warn("Could not set CPU frequency governor (cpupower may not be installed)")
    except Exception as e:
        log_warn(f"CPU frequency governor setup failed: {e}")
    
    # 7. NUMA check and recommendation
    numa_path = Path('/sys/devices/system/node/node1')
    if numa_path.exists():
        log_info("Multi-socket NUMA system detected. Recommendation: use --numa distribute flag for better performance")
    
    # 8. Reduce swappiness
    swappiness_path = Path('/proc/sys/vm/swappiness')
    if have_root and swappiness_path.exists():
        try:
            log_success("Reducing swappiness to prefer RAM over swap...")
            with open(swappiness_path, 'w') as f:
                f.write('10')
        except Exception as e:
            log_warn(f"Swappiness reduction failed: {e}")
    
    os.chmod(restore_script_path, 0o755)
    
    mem_after = get_memory_stats()
    mem_freed = max(0, mem_after - mem_before)
    
    print()
    log_success("Resources reclaimed. System state optimized for LLM inference.")
    if mem_freed > 0:
        log_info(f"Approximately {mem_freed} MB freed.")
    log_info(f"Services stopped: {stopped_count}")
    log_info(f"Restore script written to: {restore_script_path}")
    
    return 0

def optimize_windows() -> int:
    """Optimize Windows system"""
    log_info("Optimizing Windows system...")
    
    mem_before = get_memory_stats()
    
    try:
        # 1. Clear temporary files
        temp_paths = [
            os.path.expandvars(r'%TEMP%'),
            os.path.expandvars(r'%WINDIR%\Temp'),
        ]
        
        for temp_path in temp_paths:
            if os.path.exists(temp_path):
                log_success(f"Clearing {temp_path}...")
                try:
                    subprocess.run(['cmd', '/c', f'for /d %x in ({temp_path}\\*) do @rd /s /q "%x"'],
                                 capture_output=True)
                    subprocess.run(['cmd', '/c', f'del /q {temp_path}\\*'],
                                 capture_output=True)
                except Exception as e:
                    log_warn(f"Failed to clear {temp_path}: {e}")
        
        # 2. Clear memory cache via PowerShell
        try:
            log_success("Clearing memory cache...")
            subprocess.run(['powershell', '-NoProfile', '-Command',
                          'Get-ChildItem -Path "$env:TEMP" -Force | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue'],
                         capture_output=True)
        except Exception as e:
            log_warn(f"Cache clear failed: {e}")
        
        # 3. Disable CPU parking
        try:
            log_success("Disabling CPU parking...")
            subprocess.run(['powercfg', '-setacvalueindex', 'scheme_current', 'sub_processor', 'CPMINCORES', '100'],
                         capture_output=True)
        except Exception as e:
            log_warn(f"CPU parking disable failed: {e}")
        
        # 4. Switch to High Performance power plan
        try:
            log_success("Switching to High Performance power plan...")
            subprocess.run(['powercfg', '/setactive', '8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c'],
                         capture_output=True)
        except Exception as e:
            log_warn(f"Power plan switch failed: {e}")
        
        # 5. Elevate llama process priority
        try:
            log_success("Setting llama process priority to High...")
            subprocess.run(['powershell', '-NoProfile', '-Command',
                          'Get-Process llama* -ErrorAction SilentlyContinue | ForEach-Object { $_.PriorityClass = "High" }'],
                         capture_output=True)
        except Exception as e:
            log_warn(f"Process priority elevation failed: {e}")
        
    except Exception as e:
        log_error(f"Windows optimization failed: {e}")
        return 1
    
    mem_after = get_memory_stats()
    mem_freed = max(0, mem_after - mem_before)
    
    print()
    log_success("Resources reclaimed. System state optimized for LLM inference.")
    if mem_freed > 0:
        log_info(f"Approximately {mem_freed} MB freed.")
    
    return 0

def optimize_macos() -> int:
    """Optimize macOS system"""
    log_info("Optimizing macOS system...")
    
    mem_before = get_memory_stats()
    
    try:
        # 1. Purge memory
        log_success("Purging memory...")
        subprocess.run(['purge'], capture_output=True, check=False)
        
        # 2. MLX upgrade reminder
        log_info("Recommendation: Run 'pip install --upgrade mlx mlx-lm' for latest Metal shader improvements")
        
    except Exception as e:
        log_error(f"macOS optimization failed: {e}")
        return 1
    
    mem_after = get_memory_stats()
    mem_freed = max(0, mem_after - mem_before)
    
    print()
    log_success("Resources reclaimed. System state optimized for LLM inference.")
    if mem_freed > 0:
        log_info(f"Approximately {mem_freed} MB freed.")
    
    return 0

def main():
    """Main entry point"""
    system = get_platform()
    
    print()
    log_info(f"Executing Lumina Edge System Optimization ({system})...")
    print()
    
    if system == 'linux':
        return optimize_linux()
    elif system == 'windows':
        return optimize_windows()
    elif system == 'darwin':
        return optimize_macos()
    else:
        log_error(f"Unsupported platform: {system}")
        return 1

if __name__ == '__main__':
    sys.exit(main())
