#!/usr/bin/env bash
# ==============================================================================
# Lumina Edge: Linux System Resource Reclamation
# Objective: Free system memory before LLM inference
# ==============================================================================
# NOTE: Requires root/sudo privileges.
#       Services are stopped for this session only.
#       A restore script is written to /tmp so you can re-enable them.
# ==============================================================================

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
GRAY='\033[0;90m'
NC='\033[0m' # No Color

echo -e "${CYAN}[INIT] Executing Lumina Edge System Optimization...${NC}"

# ------------------------------------------------------------------
# Check for root privileges
# ------------------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
    echo -e "${YELLOW}[WARN] Not running as root. Some optimizations will be skipped.${NC}"
    echo -e "${YELLOW}       Re-run with sudo for full memory reclamation.${NC}"
    HAVE_ROOT=false
else
    HAVE_ROOT=true
fi

# ------------------------------------------------------------------
# 1. Record memory before optimization
# ------------------------------------------------------------------
MEM_BEFORE=$(awk '/MemAvailable/ {print $2}' /proc/meminfo 2>/dev/null || echo "0")

# ------------------------------------------------------------------
# 2. Drop filesystem caches (requires root)
# ------------------------------------------------------------------
if $HAVE_ROOT; then
    echo -e "${GREEN}[+] Syncing filesystem and dropping caches...${NC}"
    sync
    echo 3 > /proc/sys/vm/drop_caches 2>/dev/null || true
    echo -e "${GRAY}[+] Page cache, dentries, and inodes freed.${NC}"
else
    echo -e "${GRAY}[~] Cache drop skipped (requires root).${NC}"
fi

# ------------------------------------------------------------------
# 3. Compact memory (requires root, kernel 4.6+)
# ------------------------------------------------------------------
if $HAVE_ROOT && [[ -f /proc/sys/vm/compact_memory ]]; then
    echo -e "${GREEN}[+] Compacting memory...${NC}"
    echo 1 > /proc/sys/vm/compact_memory 2>/dev/null || true
else
    echo -e "${GRAY}[~] Memory compaction skipped.${NC}"
fi

# ------------------------------------------------------------------
# 4. Stop non-critical services (systemd)
#    These are the Linux equivalents of the Windows services
#    that the PowerShell optimizer targets.
# ------------------------------------------------------------------
# Services to consider stopping:
#   tracker-miner-fs-3 / tracker-miner-fs  — file indexer (~equivalent to WSearch)
#   packagekit                              — background package manager
#   fwupd                                   — firmware update daemon
#   snapd                                   — snap package daemon
#   unattended-upgrades                     — automatic updates

RESTORE_SCRIPT="/tmp/lumina_restore_services.sh"
echo "#!/usr/bin/env bash" > "$RESTORE_SCRIPT"
echo "# Auto-generated by optimize_system.sh — safe to delete" >> "$RESTORE_SCRIPT"
echo "# Run with sudo to restore services" >> "$RESTORE_SCRIPT"

TARGET_SERVICES=(
    "tracker-miner-fs-3.service"
    "tracker-miner-fs.service"
    "packagekit.service"
    "fwupd.service"
    "snapd.service"
    "unattended-upgrades.service"
)

STOPPED_COUNT=0

if $HAVE_ROOT; then
    for svc in "${TARGET_SERVICES[@]}"; do
        # Check if the service exists and is active
        if systemctl is-active --quiet "$svc" 2>/dev/null; then
            echo -e "${YELLOW}[-] Suspending $svc...${NC}"
            systemctl stop "$svc" 2>/dev/null || true
            echo "systemctl start $svc 2>/dev/null || true" >> "$RESTORE_SCRIPT"
            ((STOPPED_COUNT++)) || true
        elif systemctl list-unit-files "$svc" 2>/dev/null | grep -q "$svc"; then
            echo -e "${GRAY}[~] $svc exists but is not running, skipping.${NC}"
        else
            echo -e "${GRAY}[~] $svc not found, skipping.${NC}"
        fi
    done
else
    echo -e "${GRAY}[~] Service suspension skipped (requires root).${NC}"
fi

# Also try to stop user-level tracker services (GNOME)
if command -v tracker3 &>/dev/null; then
    echo -e "${YELLOW}[-] Pausing GNOME Tracker indexer...${NC}"
    tracker3 pause -s "Lumina Edge optimization" 2>/dev/null &
    echo "tracker3 resume -s 'Lumina Edge optimization' 2>/dev/null || true" >> "$RESTORE_SCRIPT"
elif command -v tracker &>/dev/null; then
    echo -e "${YELLOW}[-] Pausing GNOME Tracker indexer...${NC}"
    tracker daemon --pause="Lumina Edge optimization" 2>/dev/null || true
    echo "tracker daemon --resume='Lumina Edge optimization' 2>/dev/null || true" >> "$RESTORE_SCRIPT"
fi

# ------------------------------------------------------------------
# 5. Disable transparent huge pages (reduces CPU overhead during
#    tensor dequantization, similar to disabling memory compression)
# ------------------------------------------------------------------
if $HAVE_ROOT && [[ -f /sys/kernel/mm/transparent_hugepage/enabled ]]; then
    THP_BEFORE=$(sed -n 's/.*\[\([^]]*\)\].*/\1/p' /sys/kernel/mm/transparent_hugepage/enabled 2>/dev/null | head -n 1)
    THP_BEFORE="${THP_BEFORE:-always}"
    echo -e "${GREEN}[+] Disabling Transparent Huge Pages (was: $THP_BEFORE)...${NC}"
    echo madvise > /sys/kernel/mm/transparent_hugepage/enabled 2>/dev/null || true
    echo "echo $THP_BEFORE > /sys/kernel/mm/transparent_hugepage/enabled 2>/dev/null || true" >> "$RESTORE_SCRIPT"
fi

# ------------------------------------------------------------------
# 6. Tune swappiness to prefer RAM over swap
# ------------------------------------------------------------------
if $HAVE_ROOT; then
    SWAP_BEFORE=$(cat /proc/sys/vm/swappiness 2>/dev/null || echo "60")
    echo -e "${GREEN}[+] Reducing swappiness (was: $SWAP_BEFORE, setting to: 10)...${NC}"
    echo 10 > /proc/sys/vm/swappiness 2>/dev/null || true
    echo "echo $SWAP_BEFORE > /proc/sys/vm/swappiness 2>/dev/null || true" >> "$RESTORE_SCRIPT"
fi

chmod +x "$RESTORE_SCRIPT" 2>/dev/null || true

# ------------------------------------------------------------------
# 7. Report results
# ------------------------------------------------------------------
MEM_AFTER=$(awk '/MemAvailable/ {print $2}' /proc/meminfo 2>/dev/null || echo "0")
MEM_FREED=$(( (MEM_AFTER - MEM_BEFORE) / 1024 ))

echo ""
echo -e "${CYAN}[SUCCESS] Resources reclaimed. System state optimized for LLM inference.${NC}"
if [[ $MEM_FREED -gt 0 ]]; then
    echo -e "${GREEN}[INFO] Approximately ${MEM_FREED} MB freed.${NC}"
fi
echo -e "${GRAY}[INFO] Services stopped: $STOPPED_COUNT${NC}"
echo -e "${GRAY}[INFO] Restore script written to: $RESTORE_SCRIPT${NC}"
echo -e "${GRAY}[INFO] Services will restore on next reboot, or run the restore script manually.${NC}"
